### ISSUE TITLE
Poppins and Noto Sans fonts don't download on my Linux box and substitute to some ugly Serif font

### ISSUE THREAD

**Issue by MrCsabaToth** [ampproject/amp.dev#5435] opened 2021-02-23 18:04 UTC
### Current behavior
I'm visiting "Best practices for creating a successful Web Story" Guides & Tutorials and it shows up weird. Interestingly other pages are mostly OK, so maybe something differs with this guide for some reason? Or this was the only one I reloaded?

Please also provide:
- Page link: https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories
- (Optional) Screenshots/videos:
Firefox:
![Screenshot_2021-02-23_09-59-34](https://user-images.githubusercontent.com/744949/108886771-38ac8b00-75be-11eb-8bf2-6658f7513443.png)

FF console:
![Screenshot_2021-02-23_09-59-55](https://user-images.githubusercontent.com/744949/108886786-3d713f00-75be-11eb-906e-9fd90126000c.png)
```
Powered by AMP ⚡ HTML – Version 2102060044003 https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories v0.mjs:10:180403
downloadable font: font-display timeout, webfont not used (font-family: "Noto Sans" style:normal weight:400 stretch:100 src index:2) source: https://amp.dev/static/fonts/noto-sans-v7-latin-regular.woff2
https://amp.dev/static/fonts/poppins-v5-latin-700.woff2
downloadable font: font-display timeout, webfont not used (font-family: "Poppins" style:normal weight:700 stretch:100 src index:2) source: https://amp.dev/static/fonts/poppins-v5-latin-700.woff2
```

Chrome stable
![Screenshot_2021-02-23_10-01-05](https://user-images.githubusercontent.com/744949/108886835-4d891e80-75be-11eb-8c34-e6f1a8541dd3.png)
![Screenshot_2021-02-23_10-01-25](https://user-images.githubusercontent.com/744949/108886843-511ca580-75be-11eb-8407-4db8804ed636.png)

Chrome dev doesn't show the thin ugly extra scrollbar!
![Screenshot_2021-02-23_10-01-43](https://user-images.githubusercontent.com/744949/108886893-5e399480-75be-11eb-8d67-bd002891e28d.png)

### Expected behavior/code
Since the woff2 files are there, I'd expect them to be used, at least after they are downloaded. I've spent plenty of time researching how I should approach font loading for my blog. There are endless possibilities. We just shouldn't be the slave of the Lighthouse numbers so much to let the ugly serif font stay and don't substitute it just because it'd increase the CLS / Cumulative Layout Shift. (I'm not sure that's the reason, but at least Firefox's debug console reveals that the reason for not showing the `woff2` fonts is a timeout). I'm on broadband with a desktop laptop so I have enough bandwidth and umph as well. On my personal blog I host the `ttf` and `woff` versions of my font and the woff2s come from CDN. I use `swap` `font-display` CSS directive to give infinite time for a substitution. `fallback` directive has a short swap period, but I'm not sure if that's the case because the site loads quite fast.

### Reproduction procedure
Please provide the steps to reproduce the problem:

1. Visit https://amp.dev/documentation/guides-and-tutorials/start/create_successful_stories/?format=stories
2. If it shows up fine for whatever reason than press reload and wait
3. If it still shows up fine for whatever reason than press reload and wait again

- What browser are you using?
FF 83.0 (64-bit), Chrome 89.0.4389.58 (Official Build) beta (64-bit), Chrome 90.0.4421.5 (Official Build) dev (64-bit)

- What O/S are you using?
Devuan GNU/Linux 4 (chimaera/ceres)
That's basically a Debian Sid.

**Comment by MrCsabaToth** [comment] 2021-02-23 18:04
Somewhat relates to https://github.com/ampproject/amp.dev/issues/5336

**Comment by patrickkettner** [comment] 2021-02-23 18:31
Thanks for the report! it is a dupe of #5336, like you said, so closing in favor of it

**Closed by patrickkettner** 2021-02-23 18:31 UTC
Labels: Status: Pending Triage, Type: Bug

**Comment by MrCsabaToth** [comment] 2021-02-23 18:40
> Thanks for the report! it is a dupe of #5336, like you said, so closing in favor of it

Well, I'm not sure. Because #5336 is only about substitution and I fear that #5336 may not make the Poppins and Mono Sans appear, just some Sans Serif substitute. I haven't dig enough to see if the particular tutorial page may have some bug in it vs the other pages.

**Comment by patrickkettner** [comment] 2021-02-23 18:46
It effects all pages. it is because of a CSS change we merged recently on
font-display.
