### ISSUE TITLE
Internal server error when button Login to comment

### ISSUE THREAD

**Issue by Kifsif** [ampproject/amp.dev#3679] opened 2020-03-12 06:08 UTC
### Current behavior
Button "Login to comment" causes internal server error (500)

Please also provide:
- Page link: 
This section of the tutorial:
https://amp.dev/documentation/guides-and-tutorials/develop/login_requiring/login/?format=websites

We are shown a page link. This direct link:
https://amp.dev/documentation/examples/interactivity-dynamic-content/comment_section/preview/?format=websites

- (Optional) Screenshots/videos:
[URL=https://radikalno.ru/full/2020/3/12/0b60614152ddcc65406036fec22de7f1-full.png.html][IMG]https://cdn1.radikalno.ru/uploads/2020/3/12/0b60614152ddcc65406036fec22de7f1-prev.png[/IMG][/URL] [URL=https://radikalno.ru/]радикал[/URL]

- What browser are you using?
Chrome

- What O/S are you using?
Ubuntu

**Comment by sebastianbenz** [comment] 2020-03-16 13:57
Duplicate of #3355

**Closed by sebastianbenz** 2020-03-16 13:57 UTC
Labels: Status: Pending Triage, Type: Bug
