### ISSUE TITLE
amp-autocomplete documentation should link to example page

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#3005] opened 2019-09-20 19:30 UTC
Currently amp-autocomplete [documentation](https://amp.dev/documentation/components/amp-autocomplete/) states for Examples, "AMP by Example coming soon". This should be updated to the link to the [example page](https://amp.dev/documentation/examples/components/amp-autocomplete/).

**Comment by sebastianbenz** [comment] 2019-09-23 08:07
Duplicate of #2114

**Closed by sebastianbenz** 2019-09-23 08:07 UTC
Labels: Category: Content
