### ISSUE TITLE
Pixi: "Take action" stuck at "Analyzing"

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4572] opened 2020-09-16 21:26 UTC
I saw this while analyzing camp.samples.amp.dev on my Mac on ChromeOS:

![image](https://user-images.githubusercontent.com/29419498/93394059-9388cc00-f841-11ea-8f46-2a9c2c98c912.png)

I also see this error in the Console:

![image](https://user-images.githubusercontent.com/29419498/93394085-9f748e00-f841-11ea-8273-cd87ef5012ed.png)

Here's the minified JS that threw the error:

![image](https://user-images.githubusercontent.com/29419498/93394138-bca95c80-f841-11ea-8a88-de2932647fac.png)

**Comment by patrickkettner** [comment] 2020-09-16 21:27
dupe of #4570

**Closed by patrickkettner** 2020-09-16 21:28 UTC
Labels: Category: Pixi, Status: Pending Triage, Type: Bug
