### ISSUE TITLE
amp.dev isn't importing documentation for amp-stream-gallery

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#5271] opened 2021-01-27 23:18 UTC
GH documentation here:
https://github.com/ampproject/amphtml/blob/master/extensions/amp-stream-gallery/amp-stream-gallery.md

But doesn't appear in component TOC

<img width="232" alt="Screen Shot 2021-01-27 at 3 17 56 PM" src="https://user-images.githubusercontent.com/23297417/106067113-d6da2d80-60b2-11eb-86fe-d7f0d06e47c6.png">

**Comment by patrickkettner** [comment] 2021-01-30 07:22
this is happening because `amp-stream-gallery` is not passing the validator, currently. Opened a [bug upstream](https://github.com/ampproject/amphtml/issues/32313) about it

**Comment by patrickkettner** [comment] 2021-02-02 16:01
the module isn't considered "released", so closing this as "working as intended"

**Closed by patrickkettner** 2021-02-02 16:01 UTC
Labels: Status: Blocked, Type: Bug
