### ISSUE TITLE
Rich Media Notifications do not show as mentioned

### ISSUE THREAD

**Issue by onigetoc** [ampproject/amp.dev#3487] opened 2020-02-06 15:11 UTC
This example do not work as expected on mobile.
https://amp.dev/documentation/examples/multimedia-animations/rich_media_notifications/
test:
https://gitcdn.xyz/cdn/ampproject/amp.dev/2e084222deb7058846829ae4118ad4482d8a10be/examples/source/multimedia-animations/Rich_Media_Notifications.html

**Comment by matthiasrohmer** [comment] 2020-02-06 15:23
Can you provide some more information? Which device did you use for testing, which browser in which version, ... this would help us with debugging 🙂

**Comment by onigetoc** [comment] 2020-02-06 17:52
On my Android phone Samsung 7, i just saw the usual default video or audio player

**Comment by sebastianbenz** [comment] 2020-02-06 19:37
This is working as intended - the player on the page does not change. When you lock your phone you'll see the Android buttons to start and stop playback.

**Comment by sebastianbenz** [comment] 2020-02-07 06:09
Closing for now, please reopen if there's an actual error.

**Closed by sebastianbenz** 2020-02-07 06:09 UTC
Labels: Category: Examples, P2: Medium, Type: Bug
