### ISSUE TITLE
Consent example for stories is broken

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/amp.dev#5249] opened 2021-01-22 15:22 UTC
The [example](https://amp.dev/documentation/examples/user-consent/story_user_consent/#development=1) is AMP-invalid and the demo iframe is pointing to the gone amp-by-example.appspot.com domain.

**Comment by patrickkettner** [comment] 2021-03-22 16:46
dupe of #5403, which was fixed by #5412

**Closed** 2021-03-22 16:46 UTC
Labels: Category: Examples, P1: High, Type: Bug
