### ISSUE TITLE
amp-lightbox-gallery sample is broken

### ISSUE THREAD

**Issue by siddhantdante** [ampproject/amp.dev#3505] opened 2020-02-10 08:35 UTC
amp-lightbox-gallery is not working on your website and it is also not working with react library.

[checkout on this url.](https://amp.dev/documentation/examples/components/amp-lightbox-gallery/)

**Comment by matthiasrohmer** [comment] 2020-02-10 09:24
Thanks for reporting! Indeed the sample on amp.dev is broken - we'll fix it. Can you elaborate on what "not working with react library" means in this context?

**Comment by sebastianbenz** [comment] 2020-02-10 12:03
Duplicate of #2759. I briefly looked into this a while ago, but couldn't see anything wrong.

**Closed by sebastianbenz** 2020-02-10 12:03 UTC
Labels: Category: Examples, P2: Medium, Type: Bug

**Comment by siddhantdante** [comment] 2020-02-10 12:39
i am putting amp-lightbox-gallery script in my index.html of my project
then the lightbox carousel is not working but if i am putting script tag in
helmet in any components then the lightbox is working. but if i got to home
page and then if try to comeback to the same component the script tag
throws error "loading script tag again not allowed".

**Comment by sebastianbenz** [comment] 2020-02-10 13:07
@Siddhant: could you please share a link to your page?

>
