### ISSUE TITLE
Exclude importing certain reference docs 

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#3683] opened 2020-03-13 00:05 UTC
### Problem
We import reference files from the AMPHTML repository, but some components may need to be excluded, such as [`amp-font`](https://github.com/ampproject/amphtml/blob/master/extensions/amp-font/amp-font.md) whose functionality is obsolete due to `font-display`.  

### Solution
Possibly add an exclude list here: https://github.com/ampproject/amp.dev/blob/2856b8a5691da5b5dd6493f0163b7766d24f09e8/platform/config/imports/componentReference.json

Filter it out during the importing process:
https://github.com/ampproject/amp.dev/blob/2856b8a5691da5b5dd6493f0163b7766d24f09e8/platform/lib/pipeline/componentReferenceImporter.js

### Alternatives
Sorry if this already exists! Point me to where and I'll remove `amp-font`. 

Thanks :)

**Comment by sebastianbenz** [comment] 2020-03-13 08:15
Duplicate of #3663

**Closed by sebastianbenz** 2020-03-13 08:15 UTC
Labels: P0: Critical, Status: Pending Triage, Type: Bug, Type: Feature
