### ISSUE TITLE
amp-accordion documentation does not install amp-bind

### ISSUE THREAD

**Issue by caroqliu** [ampproject/amp.dev#4828] opened 2020-10-08 19:09 UTC
https://amp.dev/documentation/components/amp-accordion/#[data-expand]

![image](https://user-images.githubusercontent.com/10456171/95502747-48f9fb80-0978-11eb-9df5-5e7217b57f96.png)

**Comment by morsssss** [comment] 2020-11-18 23:14
I think this is another instance of https://github.com/ampproject/amp.dev/issues/3911 .

**Comment by matthiasrohmer** [comment] 2021-02-10 10:31
`amp-bind` is on the documentation page itself but is lacking for the iframe at https://preview.amp.dev/documentation/components/amp-accordion.example.4.html#amp=1

**Comment by morsssss** [comment] 2021-02-10 14:00
Thanks for raising the priority, @matthiasrohmer  - it would be great to see this fixed!

**Comment by patrickkettner** [comment] 2021-04-04 21:31
closing as a dupe of #3911

**Closed by patrickkettner** 2021-04-04 21:31 UTC
Labels: Category: Functionality, P1: High, Type: Bug
