### ISSUE TITLE
amp.dev on 20-07-30

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#4252] opened 2020-07-30 19:32 UTC
is https://amp.dev/ behaving as you intended?
$home seems to be missing images and some placements seem to be 'off'
Also note that $home behaves differently in Chrome and Mozilla (each has it's uniq unexpected variation)
Desktop (Chrome) seems to render different results from mobile (Chrome)
/j

**Comment by sebastianbenz** [comment] 2020-07-30 19:44
Hm. I'm not aware of any problems. Can you post a few screenshots? Is this new?

**Comment by jaygray0919** [comment] 2020-07-30 19:56
mozilla and chrome (from my desktop)

![2020-07-30_14-52-22](https://user-images.githubusercontent.com/11330577/88968244-b0a71280-d274-11ea-9407-7d215c10d4c0.png)
![2020-07-30_14-51-31](https://user-images.githubusercontent.com/11330577/88968255-b3096c80-d274-11ea-9e24-7e50ae30598a.png)

is this different than your view?

**Comment by sebastianbenz** [comment] 2020-07-30 20:03
I can reproduce now. Looks like https://github.com/ampproject/amp.dev/issues/4128 happened again.

**Comment by jaygray0919** [comment] 2020-07-30 20:05
Good to know - thought we were having bandwidth problems :->

**Comment by sebastianbenz** [comment] 2020-07-30 20:08
Will close this issue and continue in the other one. Thanks for reporting!

**Closed by sebastianbenz** 2020-07-30 20:08 UTC
Labels: Status: Pending Triage, Type: Bug

**Comment by sebastianbenz** [comment] 2020-07-30 20:10
Should be working again. Could you verify?

**Comment by jaygray0919** [comment] 2020-07-30 20:11
FYI, we have eliminated almost all images on our planned $home site - all symbols are SVG; all images are SVG except for PNGs for customer testimonials (9 small PNGs at bottom-of-page)
/j

**Comment by jaygray0919** [comment] 2020-07-30 20:11
lemme clear cache

**Comment by jaygray0919** [comment] 2020-07-30 20:12
yup - back to normal.

**Comment by sebastianbenz** [comment] 2020-07-30 20:25
Thanks!

>
