### ISSUE TITLE
problem with installing amp.dev

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#4163] opened 2020-07-08 15:41 UTC
Am trying to install following these instructions:
  https://github.com/ampproject/amp.dev
  
Most of the install is complete (the installation is Windows Subsystem for Linux (WSL 2) Ubuntu-18.04 running under Win10)

Have successfully installed all prereqs (python2.7, grow, amp.dev from a cloned repo) and
  export AMP_DOC_TOKEN="c59f6..."

But have two problems completing the install
first, missing:  `package.json`

so i manually copied package.json **from** amp.dev **to** $home

when running: `npm run bootstrap`

get the following error:

17 verbose Linux 4.4.0-18362-Microsoft
18 verbose argv "/home/name/.nvm/versions/node/v12.18.2/bin/node" "/home/name/.nvm/versions/node/v12.18.2/bin/npm" "run" "bootstrap"
19 verbose node v12.18.2
20 verbose npm  v6.14.5
21 error code ELIFECYCLE
22 error errno 1
23 error amp-dev@1.0.5 bootstrap: `npx gulp bootstrap`
23 error Exit status 1
24 error Failed at the amp-dev@1.0.5 bootstrap script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

additional information:
`local package.json exists, but node_modules missing, did you mean to install?`

where to find `node_modules` and can i simply copy them to a target directory?

thanks for help here.

**Comment by sebastianbenz** [comment] 2020-07-09 06:21
`package.json` missing is a strong indicator for your local clone being broken - it should be there. Maybe try a fresh clone. 

Once you've cloned the repo you need to run ` npm install` which will create the `node_modules` folder for you.

**Comment by jaygray0919** [comment] 2020-07-09 10:50
Thank you Sebastian - will retrace my steps.

**Comment by jaygray0919** [comment] 2020-07-15 08:00
@sebastianbenz , I backed-up, cleaned-up, and re-started. Here's where I am now. Any obvious mistakes or omissions on my side?

`tl;dr`
problem with `AMPProject.org@ preinstall`

1) Install the LTS version of Node.js.
`nvm install --lts`

2) Install Python 2.7
*Currently running:* `Python 2.7.6`

```
echo "export PATH=\"$(python -m site --user-base)/bin\":\$PATH" >> ~/.bashrc
source ~/.bashrc
sudo apt install -y python-yaml
```

3) Install Grow
`pip install --user grow`
*successful*

4) Installed yarn
`curl -o- -L https://yarnpkg.com/install.sh | bash`
*success: installed yarn 1.22.4*
*success "saved lockfile"*

---------------------------
Fork & clone the repository
`git clone https://github.com/jaygray0919/amp.dev`
... and then install the dependencies via NPM:

`cd amp.dev`
`npm install`

*error message*
`pre-install error`

*log report:*
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/_name_/.nvm/versions/node/v12.18.2/bin/node',
1 verbose cli   '/home/_name_/.nvm/versions/node/v12.18.2/bin/npm',
1 verbose cli   'install'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose npm-session 8bf39e3fe277ffea
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall AMPProject.org@
7 info lifecycle AMPProject.org@~preinstall: AMPProject.org@
8 verbose lifecycle AMPProject.org@~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle AMPProject.org@~preinstall: PATH: /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/_name_/amp.dev/node_modules/.bin:/home/_name_/.local/bin:/home/_name_/.local/bin:/home/_name_/.yarn/bin:/home/_name_/.config/yarn/global/node_modules/.bin:/home/_name_/bin:/home/_name_/.nix-profile/bin:/home/_name_/bin:/home/_name_/.local/bin:/home/_name_/.yarn/bin:/home/_name_/.config/yarn/global/node_modules/.bin:/home/_name_/bin:/home/_name_/.nvm/versions/node/v12.18.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Python27/:/mnt/c/Python27/Scripts:/mnt/c/programdata/oracle/java/javapath:/mnt/c/program files/common files/microsoft shared/microsoft online services:/mnt/c/program files (x86)/common files/microsoft shared/microsoft online services:/mnt/c/program files/common files/microsoft shared/windows live:/mnt/c/program files (x86)/common files/microsoft shared/windows live:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/program files (x86)/windows live/shared:/mnt/c/program files (x86)/gnu/gnupg/pub:/mnt/c/program files/curl/bin:/mnt/c/bin/python:/mnt/c/bin/python/scripts:/mnt/c/program files (x86)/winmerge:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/Git/cmd:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/mnt/c/Program Files/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Google/Google Apps Migration/:/mnt/c/Users/Owner/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Owner/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/Owner/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Owner/AppData/Roaming/npm:/mnt/c/Users/Owner/.dotnet/tools
10 verbose lifecycle AMPProject.org@~preinstall: CWD: /home/_name_/amp.dev
11 silly lifecycle AMPProject.org@~preinstall: Args: [ '-c', 'node build_scripts/check-package-manager.js' ]
12 silly lifecycle AMPProject.org@~preinstall: Returned: code: 1  signal: null
13 info lifecycle AMPProject.org@~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 0ms
15 timing stage:runTopLevelLifecycles Completed in 84ms

16 verbose stack Error: AMPProject.org@ preinstall: `node build_scripts/check-package-manager.js`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
16 verbose stack     at EventEmitter.emit (events.js:315:20)
16 verbose stack     at ChildProcess.<anonymous> (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:315:20)
16 verbose stack     at maybeClose (internal/child_process.js:1021:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
17 verbose pkgid AMPProject.org@
18 verbose cwd /home/_name_/amp.dev
19 verbose Linux 4.4.0-18362-Microsoft
20 verbose argv "/home/_name_/.nvm/versions/node/v12.18.2/bin/node" "/home/_name_/.nvm/versions/node/v12.18.2/bin/npm" "install"
21 verbose node v12.18.2
22 verbose npm  v6.14.5

23 error code ELIFECYCLE
24 error errno 1
25 error AMPProject.org@ preinstall: `node build_scripts/check-package-manager.js`
25 error Exit status 1
26 error Failed at the AMPProject.org@ preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]
```
---

5) Ignored the above (to see what would happen later in workflow) and proceeded to this step:
`export AMP_DOC_TOKEN="a52e6..."`

6) Then:
`npm run bootstrap`

*consol error*
`missing script: bootstrap`

*log report*

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/_name_/.nvm/versions/node/v12.18.2/bin/node',
1 verbose cli   '/home/_name_/.nvm/versions/node/v12.18.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bootstrap'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose stack Error: missing script: bootstrap
4 verbose stack     at run (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /home/_name_/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /home/_name_/amp.dev
6 verbose Linux 4.4.0-18362-Microsoft
7 verbose argv "/home/_name_/.nvm/versions/node/v12.18.2/bin/node" "/home/_name_/.nvm/versions/node/v12.18.2/bin/npm" "run" "bootstrap"
8 verbose node v12.18.2
9 verbose npm  v6.14.5
10 error missing script: bootstrap
11 verbose exit [ 1, true ]
```

**Comment by matthiasrohmer** [comment] 2020-07-15 08:20
This looks like you are trying to install and build the deprecated ampproject.org which still lives in this repository on the `master` branch. In the log you provided there are some hints to its [package.json](https://github.com/ampproject/amp.dev/blob/master/package.json) - the problem is you are trying to do so with amp.dev's read-me from the `future` branch. We know that can cause confusion.

But it seems like the simple fix would be to checkout `future` and then try the steps again as described in the readme.

**Comment by jaygray0919** [comment] 2020-07-15 08:30
Thanks for the hints @matthiasrohmer . I'll delete the current repo, pull the `future` and retry.

**Comment by jaygray0919** [comment] 2020-07-15 09:12
@mathiasbynens Let me verify that I'm doing this correctly. I toggle the repo to: `https://github.com/jaygray0919/amp.dev/tree/future` (my HTTPS checkout was 8 days ago, but am thinking that's OK).

then, in the terminal, run: `git clone https://github.com/jaygray0919/amp.dev/tree/future`.

Is that correct?

**Comment by matthiasrohmer** [comment] 2020-07-15 09:19
Yes this should work.

**Comment by jaygray0919** [comment] 2020-07-15 09:40
from terminal, am seeing `fatal: repository 'https://github.com/jaygray0919/amp.dev/tree/future' not found`

but from the browser, this looks to be available for cloning: https://github.com/jaygray0919/amp.dev/tree/future

Is there a GitHub setting that makes `future` the default repo? Am I making some other mistake?

**Comment by matthiasrohmer** [comment] 2020-07-15 09:49
Sorry, didn't pay attention. To clone a specific branch it's: `git clone --branch future https://github.com/jaygray0919/amp.dev.git`.

`future` is set as default branch for the amp.dev repository - I think this will also apply to forks. Not quite sure why your fork has `master` as default.

**Comment by jaygray0919** [comment] 2020-07-15 09:51
Thanks - will try that next

**Comment by jaygray0919** [comment] 2020-07-15 10:05
@matthiasrohmer Look like the install is 99+% complete. Have this one error message (which may not be fatal)
error amp-dev@1.0.5 postinstall: `gulp downloadTestResources`

```
59964 verbose pkgid amp-dev@1.0.5
59965 verbose cwd /home/_name_/amp.dev
59966 verbose Linux 4.4.0-18362-Microsoft
59967 verbose argv "/home/_name_/.nvm/versions/node/v12.18.2/bin/node" "/home/_name_/.nvm/versions/node/v12.18.2/bin/npm" "install"
59968 verbose node v12.18.2
59969 verbose npm  v6.14.5
59970 error code ELIFECYCLE
59971 error errno 1
59972 error amp-dev@1.0.5 postinstall: `gulp downloadTestResources`
59972 error Exit status 1
59973 error Failed at the amp-dev@1.0.5 postinstall script.
59973 error This is probably not a problem with npm. There is likely additional logging output above.
59974 verbose exit [ 1, true ]
```
Can I ignore this error, or is there a one-liner that will `gulp downloadTestResources`
Am thinking I won't need TestResources

**Comment by matthiasrohmer** [comment] 2020-07-15 10:32
No you should do fine without the test resources (i.e. the validator) actually. Ultimately I think everything that fails now are Ubuntu (or WSL) problems for which I can only offer limited support. But let's try...

`gulp bootstrap` is actually just an aggregation task for steps that could also be done one by one. Try these one after another and see which one fails:

```bash
gulp buildComponentVersions
gulp buildBoilerplate
gulp buildPlayground
gulp importAll --queue-imports
gulp buildSamples
```

My guess is `buildBoilerplate` and `buildPlayground` will fail as they are internally relying on `childProcess`. But they can be substituted by

```bash
node boilerplate/build.js
npm run build:playground
```

**Comment by jaygray0919** [comment] 2020-07-15 10:33
Thanks. Will wrangle this now.

**Comment by jaygray0919** [comment] 2020-07-15 10:39
OK, am seeing: `No command 'gulp' found`. Does that mean the clone did not successfully install `gulp` as part of the amp.dev toolchain, or should I have installed `gulp` as part of the WSL environment (a /usr/bin utility)?

**Comment by jaygray0919** [comment] 2020-07-15 10:45
I also have access to an AWS/Nginx/Linux server. If this WSL process fails, I'll move over to our Linux server. Will check the flavor with you to make sure there is no server-flavor issues.

**Comment by jaygray0919** [comment] 2020-07-15 10:52
Will be away from my desk for 30 minutes

**Comment by matthiasrohmer** [comment] 2020-07-15 11:31
Assumed you had a global installation of gulp. Then prefix with `npx` like `npx gulp buildComponentVersions` and so on.

**Comment by jaygray0919** [comment] 2020-07-15 11:48
OK, they all fail with this (or similar) error message:
```
command failed: git config user.name
at /amp.dev/gulpfile.js/build.js:33:13
```
or
```
at /amp.dev/platform/lib/utils/git.js:24:23
```

we probably are not seeing yet-to-be-encountered issues.
i'm checking with one of my mates about using our AWS server.
when i know flavor details, i'll chech back with you to verify.
thanks for your help here Matthias

**Comment by jaygray0919** [comment] 2020-07-15 11:56
@matthiasrohmer OK, here are server details:
```
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```
Is that an acceptable platform for the amp.dev work? Do you need additional details?

**Comment by matthiasrohmer** [comment] 2020-07-15 12:05
The git error can be solved by configuring your user details like described [https://stackoverflow.com/questions/25593043/git-configuration-user-name-doesnt-work](here).

Can you tell what your plan is? I fear providing support with getting a hosted instance of amp.dev running on a third-party server is out of scope for me. Closing for now as there doesn't seem to be an actual issue that needs to be fixed.

**Closed by matthiasrohmer** 2020-07-15 12:05 UTC
Labels: Status: WIP

**Comment by jaygray0919** [comment] 2020-07-15 12:14
If we can't wrangle a solution on WSL, our plan is to use our AWS Linux box. Thanks for your help-to-date.

**Comment by matthiasrohmer** [comment] 2020-07-15 12:20
Did you try configuring git? This seems to be the last step that's missing.
