### ISSUE TITLE
amp-analytics example page broken

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#5538] opened 2021-03-18 22:22 UTC
The [amp-analytics example](https://amp.dev/documentation/examples/components/amp-analytics/?referrer=ampbyexample.com) has a lot of AMP errors
<img width="1395" alt="Screen Shot 2021-03-18 at 3 21 02 PM" src="https://user-images.githubusercontent.com/23297417/111705311-b8182d80-87fd-11eb-873d-24963e45a3af.png">
 is missing the TOC.

**Comment by patrickkettner** [comment] 2021-04-06 10:19
dupe of #4250

**Closed by patrickkettner** 2021-04-06 10:19 UTC
Labels: Status: Pending Triage, Type: Bug
