### ISSUE TITLE
Playground: "Cannot read property '0' of null"

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4566] opened 2020-09-16 17:34 UTC
I'm not sure what's causing this error to be emitted. I don't see missing functionality!

But whenever I open the AMP playground, I see this error in the Console. It finally concerned me enough to report it.

![Screen Shot 2020-09-16 at 1 34 24 PM](https://user-images.githubusercontent.com/29419498/93372079-61677200-f821-11ea-9135-73a17fbcdabd.png)

**Comment by matthiasrohmer** [comment] 2020-09-16 18:22
Duplicate of #4558, planned to look into this tomorrow 🙂

**Closed by matthiasrohmer** 2020-09-16 18:22 UTC
Labels: Status: Pending Triage, Type: Bug
