### ISSUE TITLE
Is it possible to make the carousel work from right to left? An example?

### ISSUE THREAD

**Issue by omar-dulaimi** [ampproject/amp.dev#3842] opened 2020-04-20 12:28 UTC
## 📖 Missing or Out-of-Date Documentation
components support for RTL languages
### Problem
We wanted to switch the direction of amp-carousel component from LTR to RTL since our users are mainly arabic speakers. But couldn't find anything mentioned about this in the docs.

### Content type
tutorial

**Comment by matthiasrohmer** [comment] 2020-04-20 12:41
Thanks for bringing this up! `amp-carousel` actually seems to support the `dir` attribute. Support is inherited from `amp-carousel`'s base component `amp-base-carousel` for which you'll find documentation [here](https://amp.dev/documentation/components/amp-base-carousel/#rtl).

I quickly tested this in the [AMP playground](https://playground.amp.dev/) with the following snippet:

```html
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <title>amp-carousel LTR Example</title>
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
  <script async custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js"></script>
  <style amp-custom>
    .slide {
      width: 100vw;
      height: 300px;
      background-color: gold;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>amp-carousel LTR Example</h1>
  
  <amp-carousel dir="rtl" layout="fixed-height" height="300">
	<div class="slide">
      <div>1        </div>
    </div>
    <div class="slide">
      2
    </div>
    <div class="slide">
      3
    </div>
  </amp-carousel>
</body>
</html>
``` 

Does this work as intended and solve your use case?

/cc @CrystalOnScript

**Comment by matthiasrohmer** [comment] 2020-04-20 13:03
@nainar, not quite sure if you are still the correct person to tag for all things related `amp-carousel` but: from what I know I don't think it's working as intended. I assume the arrows need to be flipped...? Is there someone on the core team familiar with building RTL web experiences?

**Comment by omar-dulaimi** [comment] 2020-04-20 16:45
Thanks a lot @matthiasrohmer for the detailed response. I tried that and it actually worked, but there might be some other details that i'm missing so I'll wait until my colleague comes online to update this response. But for me, the only thing that doesn't seem to be working fine is the arrows. They disappear after a while, although they don't in the playground example you provided above. I'll try to recreate a very simple reproduction soon as it could be a styling conflict on our end.

**Comment by matthiasrohmer** [comment] 2020-04-20 17:13
@omar-dulaimi you're welcome! Provide as many details as you can 🙂 This will help us improve the documentation as well as AMP's support for RTL websites.

Especially a reduced example with a description of your expected behavior would be awesome. Since this isn't related to the documentation anymore it'll be great if you'd open the issue in the ampproject/amphtml project. It'll also gain more attention there.

**Comment by morsssss** [comment] 2020-04-23 16:55
@omar-dulaimi , when I first used `<amp-carousel>`, I, too, was confused when my arrows vanished.

It turned out that was by design. It's now documented more clearly:

https://amp.dev/documentation/components/amp-carousel/?format=websites#controls-(optional)

Does this resolve your problem?

If you find a bug here, you can report that [in the amphtml project](https://github.com/ampproject/amphtml/issues).

**Comment by matthiasrohmer** [comment] 2020-05-14 07:15
Closing due to inactivity. Feel free to reopen if you need further support 🙂

**Comment by omar-dulaimi** [comment] 2020-06-02 10:27
Hello, Sorry for the delay. After multiple days of triage, it seems that setting rtl doesn't work properl.
While it does change the direction, it doesn't actually load all images, just the first ones.

In our case it was a carousel of 4 images, only the first two were loaded!

To try it out fast, just go here to the playground example and set dir="rtl" for the first carousel. 
https://playground.amp.dev/?url=https%3A%2F%2Fpreview.amp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-carousel&format=websites&_gl=1*ip4ars*_ga*YW1wLVAwTm9TZ0taOGlkeWZRcEhhcVlhc3c.

It will only load the first image, the rest are ignored for some reason. This behavior occurs on Chrome.

Although it seems to be working fine on Firefox.

**Comment by omar-dulaimi** [comment] 2020-06-03 20:59
Hello,
Should I open a new issue?
Just to make sure that you actually can see closed issues or not.

**Comment by matthiasrohmer** [comment] 2020-06-03 21:47
Sorry for the delay, @omar-dulaimi! I am OOO this week and therefore didn't respond. Without having taken a closer look this sounds like a bug and hence out of scope for amp.dev. We'd much appreciate you opening an issue in [ampproject/amphtml](https://github.com/ampproject/amphtml). What you summarized in https://github.com/ampproject/amp.dev/issues/3842#issuecomment-637446287 will be good starting point 🙂 Thanks in advance!

**Comment by morsssss** [comment] 2020-06-04 01:55
It sounds like two different things are happening here:

**There may be a bug in amp-carousel**. In that case, please [file an issue](https://github.com/ampproject/amphtml/issues/new/choose) on the amphtml project! This github repo is for the amp.dev site.

**We don't seem to document how to select LTR / RTL behavior**. I only saw a passing reference to this in the docs! If I'm right about that, we should create an issue to add this to the docs.

**Comment by omar-dulaimi** [comment] 2020-06-04 11:06
Thank you guys @matthiasrohmer @morsssss. I'll submit a new issue to amphtml.
Have a good weekend.

**Closed** 2020-12-04 17:08 UTC
Labels: Category: Documentation, Category: UX, P1: High, Type: Bug
