### ISSUE TITLE
Images not generated for smaller screen widths

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp.dev#4129] opened 2020-06-29 20:54 UTC
I noticed this on the [amp-script tutorial page](https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial/) on Chrome 83 on my MacBook, but I imagine it will appear elsewhere as well.

Looks like we now successfully generate images for various screen sizes - hooray! And we use `srcset` to choose the right one for the screen - also hooray! Unfortunately I don't think images are being generated in all cases for all screen sizes. Which means some images are broken.

On the page I mention, I see errors for images like `hello-amp-script.png`, `script-in-sources.png`, and `global-set.png`:

![Screen Shot 2020-06-29 at 4 45 31 PM](https://user-images.githubusercontent.com/29419498/86054722-a6e97f80-ba28-11ea-874e-22d02352918b.png)

And so we have broken images like this:

![Screen Shot 2020-06-29 at 4 45 20 PM](https://user-images.githubusercontent.com/29419498/86054742-ad77f700-ba28-11ea-965d-e16c811cfe8b.png)

If it helps, here's the HTML for the image missing above, `global-set.png`:

`<amp-img src="/static/img/docs/tutorials/custom-javascript-tutorial/global-set.png" width="563" height="38" layout="intrinsic" alt="Console message showing submitButton is set" srcset="https://amp.dev/static/img/docs/tutorials/custom-javascript-tutorial/global-set.png?width=680&hash=6fcd475355fd78f25d048ab34151f9c3aa2e42af 680w, https://amp.dev/static/img/docs/tutorials/custom-javascript-tutorial/global-set.png?width=1200&hash=6fcd475355fd78f25d048ab34151f9c3aa2e42af 1200w, https://amp.dev/static/img/docs/tutorials/custom-javascript-tutorial/global-set.png?width=1750&hash=6fcd475355fd78f25d048ab34151f9c3aa2e42af 1750w"></amp-img>`

**Comment by sebastianbenz** [comment] 2020-06-30 13:00
Duplicate of #4128

**Closed by sebastianbenz** 2020-06-30 13:00 UTC
Labels: Status: Pending Triage, Type: Bug
