### ISSUE TITLE
amp-img documentation advises antipattern of using fallbacks for WebP

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp.dev#4024] opened 2020-06-01 21:42 UTC
### Problem

The docs for `amp-img` have an example for how to specify a fallback image when the browser doesn't support WebP. The problem is that this is an antipattern, as browsers which don't support WebP will be forced to download two images: the WebP and then the JPG.

### Location

https://amp.dev/documentation/components/amp-img/#example:-specifying-a-fallback-image

### Content type

Example

**Comment by sebastianbenz** [comment] 2020-06-02 08:41
Duplicate of https://github.com/ampproject/amphtml/issues/21912#issuecomment-617995565

**Closed by sebastianbenz** 2020-06-02 08:41 UTC
Labels: Category: Content, Status: Pending Triage
