### ISSUE TITLE
How AMP works code sample causes overflow

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amp.dev#5188] opened 2021-01-11 14:36 UTC
This page: https://amp.dev/about/how-amp-works/ previously (uncertain release) worked well on mobile.

Current page in portrait on mobile is 50% of screen, and in landscape is 80% of screen.

My guess: the hamburger menu is positioned far right (off logical page) which squeezes the content portion of the page.

Situation is visible in Chrome Dev and on device.

/jay gray

**Comment by patrickkettner** [comment] 2021-01-11 14:49
thanks for the report! 

its actually a `<pre>` element being used for a code sample lower down on the page that is causing the issue but it was likely caused by something else changing recently

**Comment by jaygray0919** [comment] 2021-01-11 14:54
makes sense (a width issue on `<pre>`
the menus is a "victim"

**Comment by jaygray0919** [comment] 2021-01-11 15:00
actually, the problem persists when the `<pre>` is removed

**Comment by matthiasrohmer** [comment] 2021-01-13 12:04
@jaygray0919, is this the issue you are seeing?

![Bildschirmfoto 2021-01-13 um 13 03 44](https://user-images.githubusercontent.com/12857772/104450116-e419f700-559f-11eb-94d3-8a3346abb6d0.png)

**Comment by jaygray0919** [comment] 2021-01-13 13:06
Here's what I see in Chrome Dev and on mobile

![image](https://user-images.githubusercontent.com/11330577/104456113-d3508d80-556d-11eb-900a-6c5236f9f76e.png)

**Comment by westonruter** [comment] 2021-01-20 05:43
I'm also seeing this:

https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached/ | https://amp.dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls/
-------|-------
![amp dev_documentation_guides-and-tutorials_learn_amp-caches-and-cors_how_amp_pages_are_cached_(Moto G4)](https://user-images.githubusercontent.com/134745/105131725-5ad25b00-5a9e-11eb-8349-a9b7f3cc8c01.png) | ![amp dev_documentation_guides-and-tutorials_learn_amp-caches-and-cors_amp-cache-urls_(Moto G4) (2)](https://user-images.githubusercontent.com/134745/105132129-362ab300-5a9f-11eb-9be2-fae3a5628cc6.png)

The issue is that `code` elements and `a` elements have `word-break: normal`. This CSS fixes the issue for me:

```css
code, a {
    word-break: break-all !important;
}
```

(Naturally something other than `!important` should be used.)

**Comment by patrickkettner** [comment] 2021-01-20 06:04
@matthiasrohmer would you have a chance to look at this?

**Comment by patrickkettner** [comment] 2021-02-01 04:24
closing in favor of #5283 as it effects more than just one page

Thank you for the report, @jaygray0919!

**Closed by patrickkettner** 2021-02-01 04:25 UTC
Labels: Type: Bug
