### ISSUE TITLE
amp-bind examples do not work

### ISSUE THREAD

**Issue by CrystalOnScript** [ampproject/amp.dev#2760] opened 2019-08-13 22:16 UTC
About half of the amp-bind examples are not working:
https://amp.dev/documentation/examples/components/amp-bind/?format=websites

**Comment by sebastianbenz** [comment] 2019-08-14 08:47
I can only reproduce it for:

* Remote state
* Refresh state

because the endpoints are wrong. Are there others?

@lluerich can you please take a look.

**Comment by lluerich** [comment] 2019-08-14 09:15
There was only an issue with the endpoint of the 'Refresh state' example. Fixed in #2762. 
Some examples' state however is evaluated on first interaction with another example. So the 'Remote state' example will only work after a page reload or if it being the first sample after initial load.
Same thing goes for the 'Initializing state' example. ```[text]="undefinedText"``` is evaluated once an interaction with another example takes place.

**Comment by sebastianbenz** [comment] 2019-08-14 10:53
@CrystalOnScript any ideas how we could better explain the initialization problem @lluerich mentioned?

**Comment by lluerich** [comment] 2021-01-20 15:43
@CrystalOnScript maybe we could just add placeholders for the initial load everywhere, so that the page does not look broken on load. This is what the documentation on amp-bind recommends anyway.
Another idea would be to include something like an 'evaluate state'-button somewhere at the top so that the user can see what values are in the state after load of the page.

**Comment by CrystalOnScript** [comment] 2021-01-20 22:25
Thanks for following up on this issue @lluerich! We should follow the documentation and add placeholders, I think that's a great idea.

**Closed** 2021-01-22 12:39 UTC
Labels: Category: Documentation, Category: Examples, Type: Bug, good first issue
